-- ห้ามแก้ไฟล์นี้หลังรันแล้ว ถ้าจะเปลี่ยนตาราง ให้สร้างไฟล์ใหม่ เช่น V2__... นะเพื่อน

-- 1) users
CREATE TABLE users (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email       VARCHAR(255) NOT NULL UNIQUE,
    password    VARCHAR(255) NOT NULL,
    role        VARCHAR(20)  NOT NULL DEFAULT 'USER'
                CHECK (role IN ('USER', 'ADMIN')),
    is_active   BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at  TIMESTAMP    NOT NULL DEFAULT NOW()
);

-- 2) user_profiles (1:1 กับ users)
CREATE TABLE user_profiles (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id       BIGINT       NOT NULL UNIQUE
                  REFERENCES users (id) ON DELETE CASCADE,
    first_name    VARCHAR(100),
    last_name     VARCHAR(100),
    phone_number  VARCHAR(20),
    avatar_url    VARCHAR(500)
);

-- 3) species
CREATE TABLE species (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name                  VARCHAR(100) NOT NULL UNIQUE,
    water_interval_days   INTEGER      NOT NULL CHECK (water_interval_days > 0),
    sunlight_requirement  VARCHAR(20)
                          CHECK (sunlight_requirement IN ('LOW', 'MEDIUM', 'HIGH')),
    description           TEXT
);

-- 4) plants (N:1 users, N:1 species)
CREATE TABLE plants (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         BIGINT      NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    species_id      BIGINT      NOT NULL REFERENCES species (id) ON DELETE RESTRICT,
    nickname        VARCHAR(100),
    health_status   VARCHAR(20) NOT NULL DEFAULT 'HEALTHY'
                    CHECK (health_status IN ('HEALTHY', 'SICK', 'RECOVERING', 'DEAD')),
    recovery_count  INTEGER     NOT NULL DEFAULT 0,
    planted_date    DATE,
    created_at      TIMESTAMP   NOT NULL DEFAULT NOW()
);
CREATE INDEX idx_plants_user_id    ON plants (user_id);
CREATE INDEX idx_plants_species_id ON plants (species_id);

-- 5) care_schedules (N:1 plants)
CREATE TABLE care_schedules (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plant_id       BIGINT      NOT NULL REFERENCES plants (id) ON DELETE CASCADE,
    action_type    VARCHAR(20) NOT NULL
                   CHECK (action_type IN ('WATER', 'FERTILIZE', 'REPOT', 'CHECK_SUNLIGHT', 'HEALTH_CHECK')),
    next_due_date  DATE        NOT NULL,
    is_active      BOOLEAN     NOT NULL DEFAULT TRUE,
    UNIQUE (plant_id, action_type)
);
CREATE INDEX idx_care_schedules_due ON care_schedules (is_active, next_due_date);

-- 6) care_logs (N:1 plants, N:1 care_schedules)
CREATE TABLE care_logs (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plant_id          BIGINT      NOT NULL REFERENCES plants (id) ON DELETE CASCADE,
    care_schedule_id  BIGINT      REFERENCES care_schedules (id) ON DELETE SET NULL,
    action_type       VARCHAR(20) NOT NULL
                      CHECK (action_type IN ('WATER', 'FERTILIZE', 'REPOT', 'CHECK_SUNLIGHT', 'HEALTH_CHECK')),
    due_date          DATE,
    performed_at      TIMESTAMP   NOT NULL DEFAULT NOW(),
    notes             TEXT
);
CREATE INDEX idx_care_logs_plant_performed ON care_logs (plant_id, performed_at DESC);

-- 7) health_reports (N:1 plants)
CREATE TABLE health_reports (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plant_id     BIGINT       NOT NULL REFERENCES plants (id) ON DELETE CASCADE,
    title        VARCHAR(150) NOT NULL,
    description  TEXT,
    severity     VARCHAR(10)  CHECK (severity IN ('LOW', 'MEDIUM', 'HIGH')),
    image_url    VARCHAR(500),
    status       VARCHAR(20)  NOT NULL DEFAULT 'PENDING'
                 CHECK (status IN ('PENDING', 'IN_PROGRESS', 'RESOLVED', 'REJECTED')),
    admin_reply  TEXT,
    created_at   TIMESTAMP    NOT NULL DEFAULT NOW(),
    resolved_at  TIMESTAMP
);
CREATE INDEX idx_health_reports_plant  ON health_reports (plant_id, created_at DESC);
CREATE INDEX idx_health_reports_status ON health_reports (status);

-- 8) notifications (N:1 users, N:1 plants, N:1 care_schedules)
CREATE TABLE notifications (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id           BIGINT       NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    plant_id          BIGINT       REFERENCES plants (id) ON DELETE CASCADE,
    care_schedule_id  BIGINT       REFERENCES care_schedules (id) ON DELETE SET NULL,
    type              VARCHAR(20)  NOT NULL
                      CHECK (type IN ('CARE_DUE', 'HEALTH_REPLY', 'SYSTEM')),
    message           VARCHAR(255) NOT NULL,
    is_read           BOOLEAN      NOT NULL DEFAULT FALSE,
    created_at        TIMESTAMP    NOT NULL DEFAULT NOW()
);
CREATE INDEX idx_notifications_user_read ON notifications (user_id, is_read);